prod_1:
  title: "Polo Men's Striped Casual Shirt"
  description: "Brand new Polo striped with colours : Red,Blue,Black. Limited Pieces"
  categories:  [ "Clothing", "Mens Wear", "Shirts"]
  permalink:   "http://store.polo.com/purchase/shirt/Polo-Mens-Striped-Casual-Shirt"
  stock:       67
  price:       1999
  discount:    0
  incltax:     true
  shipment:    65.0
  cod:         true
  offer:       false
  offerdesc:   null
  dpimg:        'http://www.badhaven.com/wp-content/uploads/2012/07/noImageAvailable300.gif'
  screenshots: ['http://www.badhaven.com/wp-content/uploads/2012/07/noImageAvailable300.gif']
  tags: ['polo','shirt','limited']

prod_2:
  title: "Polo Women's Striped Shirt"
  description: null
  categories:  [ "Clothing", "Womens Wear", "Shirts"]
  permalink:   "http://store.polo.com/purchase/shirt/Polo-womens-Striped-Casual-Shirt"
  stock:       77
  price:       1799
  discount:    0
  incltax:     true
  shipment:    65.0
  cod:         true
  offer:       false
  offerdesc:   null
  dpimg:        'http://www.badhaven.com/wp-content/uploads/2012/07/noImageAvailable300.gif'
  screenshots: []
  tags: ['Branded','Stylish','limited']

prod_3:
  title: 'sample'
  description: 'sample'
  categories:  ['sample']
  permalink:  ''
  stock:   0
  price:   0
  discount:  0
  incltax:   true
  shipment:  0
  cod:    false
  offer:   false
  offerdesc:  ''
  dpimg:  'http://www.badhaven.com/wp-content/uploads/2012/07/noImageAvailable300.gif'
  screenshots: []
  tags: ['sample']

prod_4:
  title: 'sample'
  description: 'sample'
  categories:  ['sample']
  permalink:  ''
  stock:   0
  price:   0
  discount:  0
  incltax:   true
  shipment:  0
  cod:    false
  offer:   false
  offerdesc:  ''
  dpimg:  'http://www.badhaven.com/wp-content/uploads/2012/07/noImageAvailable300.gif'
  screenshots: []
  tags: ['sample']

#prod_2:
#  title:
#  description:
#  categories:  ['','']
#  permalink:
#  stock:
#  price:
#  discount:
#  incltax:
#  shipment:
#  cod:
#  offer:
#  offerdesc:
#  dpimg:
#  screenshots: ['','','']
#  tags: ['','','']

#prod_2:
#  title:
#  description:
#  categories:  ['','']
#  permalink:
#  stock:
#  price:
#  discount:
#  incltax:
#  shipment:
#  cod:
#  offer:
#  offerdesc:
#  dpimg:
#  screenshots: ['','','']
#  tags: ['','','']

#prod_2:
#  title:
#  description:
#  categories:  ['','']
#  permalink:
#  stock:
#  price:
#  discount:
#  incltax:
#  shipment:
#  cod:
#  offer:
#  offerdesc:
#  dpimg:
#  screenshots: ['','','']
#  tags: ['','','']

#prod_2:
#  title:
#  description:
#  categories:  ['','']
#  permalink:
#  stock:
#  price:
#  discount:
#  incltax:
#  shipment:
#  cod:
#  offer:
#  offerdesc:
#  dpimg:
#  screenshots: ['','','']
#  tags: ['','','']